---
- name: k8s-manager
  box: bento/debian-10
  hostname: k8s-manager
  ipaddress: 192.168.56.3
  memory: 2048
  cpus: 2
  provision: provision/shell/k8s-manager.sh

- name: k8s-worker01
  box: bento/debian-10
  hostname: k8s-worker01
  ipaddress: 192.168.56.4
  memory: 2048
  cpus: 2
  provision: provision/shell/k8s-worker.sh

- name: k8s-worker02
  box: bento/debian-10
  hostname: k8s-worker02
  ipaddress: 192.168.56.5
  memory: 2048
  cpus: 2
  provision: provision/shell/k8s-worker.sh
